### ISSUE TITLE
Expose `_cache` property

### ISSUE THREAD

**Issue by ndrwrbgs** [maldworth/CacheManager.FileCaching#2]
The `FileCache _cache` property exposes the functionality of `FileCache` (like max cache size, accesstimeout, ShrinkCacheToSize) that might be beneficial to have accessible in some way. Unfortunately, `CacheManager` library won't give me the Handle directly (I have to access it via the list of handles) anyway, so since I already have to do an unsafe case to get `FileCacheHandle`, it might not be that much worse to just use Reflection to get `_cache`, so I'd consider this a definitely "feature request"/"what do you think" rather than anything like a bug report.

BTW thank you for making this. I've wanted it for a couple years for devbox testing, finally got around to making my own (rough draft) today, just to find this implementation _FINALLY_ :heart:

**Comment by maldworth** [comment]
I'd like to follow the pattern from MichaCo/CacheManager and not expose the underlying handle to protect people from themselves :). Is there something in particular you are accessing from the FileCache directly? Could we expose those through some additional get methods on the FileCacheHandle?

**Comment by ndrwrbgs** [comment]
Exposing was just the easier solution, I agree with you that it's a better
design to pipe through any relevant parts from this library :)

The main things I was interesting in were it's cleaning ability based on
size since I'd be afraid using in production any unbounded size cache.

**Comment by maldworth** [comment]
For this one, please make a PR and expose what you'd like from FileCache.

**Comment by ndrwrbgs** [comment]
Given a major v3 change coming over there, I'm going to delay this work. Feel free to close this if you like to keep your inbox clean, otherwise leave it to ping me later when I forget :-P

**Comment by maldworth** [comment]
v3 of FileCache is out. You can continue this when ready

**Comment by ndrwrbgs** [comment]
Looks like you exposed it for me :-P
https://github.com/maldworth/CacheManager.FileCaching/blob/c5db949c3af83b89dc8753d1f0b331c3d93703d7/src/CacheManager.FileCaching/FileCacheHandle.cs#L75

The usages I had so far were involving how FileCache doesn't have timer-based cleaning, the sliding support, and debugging some other things. I think it's mostly an artifact of that library still being under active development - I think when/if it goes through a burst of stabilization/bug-bash and then settles down, hiding more things and exposing only controlled views of it makes a lot of sense, but right now the ease of direct access while it's still undergoing changes is nice :)

Fortunately, since Reflection is a thing (and, from the above, I don't expect this to be a forever-thing) there are no scenarios blocked even if the `FileCache` is hidden again, so I will mark this closed.
