### ISSUE TITLE
Consider removing `isBackplaneSource` from `WithFileCacheHandle`

### ISSUE THREAD

**Issue by ndrwrbgs** [maldworth/CacheManager.FileCaching#4]
Since there isn't an implementation of `CacheBackplane` (and `FileCache` library doesn't expose update events based on, e.g. `FileSystemWatcher`), it would seem there isn't a way to actually use the Handle as a backplane source

**Comment by ndrwrbgs** [comment]
If interested in adding though, I _think_ something as simple as this would work. That said, it's maybe a functionality that (in part) we'd want to push into `FileCache` (since it requires information about how `FileCache` stores items to be functional, and would break if, say, https://github.com/acarteas/FileCache/issues/16 were changed)

```C#
class FileCacheBackplane : CacheBackplane
    {
        private FileSystemWatcher fileSystemWatcher;

        public FileCacheBackplane(
            ICacheManagerConfiguration configuration,
            FileCache fileCache)
            : base(configuration)
        {
            this.fileSystemWatcher = new FileSystemWatcher(Path.Combine(fileCache.CacheDir, "cache") /* todo: abstraction leak */);
            this.fileSystemWatcher.Created += Fsw_Created;
            this.fileSystemWatcher.Error += Fsw_Error;
            this.fileSystemWatcher.Deleted += Fsw_Deleted;
            this.fileSystemWatcher.Changed += FileSystemWatcher_Changed;

            this.fileSystemWatcher.EnableRaisingEvents = true;
        }

        private void FileSystemWatcher_Changed(object sender, FileSystemEventArgs e)
        {
            this.TriggerChanged(
                Path.GetFileNameWithoutExtension(e.Name),
                CacheItemChangedEventAction.Update);
        }

        protected override void Dispose(bool managed)
        {
            base.Dispose(managed);
            this.fileSystemWatcher.Dispose();
        }

        public override void NotifyChange(string key, CacheItemChangedEventAction action)
        {
        }

        public override void NotifyChange(string key, string region, CacheItemChangedEventAction action)
        {
        }

        public override void NotifyClear()
        {
        }

        public override void NotifyClearRegion(string region)
        {
        }

        public override void NotifyRemove(string key)
        {
        }

        public override void NotifyRemove(string key, string region)
        {
        }

        private void Fsw_Deleted(object sender, FileSystemEventArgs e)
        {
            this.TriggerRemoved(Path.GetFileNameWithoutExtension(e.Name));
        }

        private void Fsw_Error(object sender, ErrorEventArgs e)
        {
            throw new NotImplementedException();
        }

        private void Fsw_Created(object sender, FileSystemEventArgs e)
        {
            this.TriggerChanged(
                Path.GetFileNameWithoutExtension(e.Name),
                CacheItemChangedEventAction.Add);
        }
    }
```

**Comment by maldworth** [comment]
Interesting. My use case never needed a backplane, so I didn't bother implementing it. I guess if you were to implement a backplane, it would need to be on the same physical server (or I guess file system watcher could point to a network mounted drive).

So I think a feature like this could provide some value, but as you mentioned, some bits might make sense to put in the underlying library FileCache.

**Comment by ndrwrbgs** [comment]
For the implementation here, I would suggest we just remove the `isBackplane` for now and set it to false when passing off to `CacheManager`, would that make sense to do?

What I want to avoid is a user setting true and thinking then that they have a backplane.

**Comment by maldworth** [comment]
So the isBackplane parameter is part of the `public sealed class CacheHandleConfiguration` which is in CacheManager.Core. So I don't really have any options here to remove that. The best I can do is throw an exception in the constructor if the user sets it to true. Would that be okay?

**Comment by ndrwrbgs** [comment]
Oh we definitely can't change their API, but this issue was for
WithFileCacheHandle which is controlled in this library (with the
suggestion being to pass false).

**Comment by maldworth** [comment]
oops, I think that's just a comment error. If you look in the file, it never actually has a parameter for backplane, just in the xml comment. I can fix that.

https://github.com/maldworth/CacheManager.FileCaching/blob/develop/src/CacheManager.FileCaching/FileCachingBuilderExtensions.cs

**Comment by ndrwrbgs** [comment]
Looks like you removed it last month
https://github.com/maldworth/CacheManager.FileCaching/commit/5ec0bf0f086b2973e75c714b7dbb25975f73c93e#diff-e969ea7c13c67119365c21684ac79920 :-P
