### ISSUE TITLE
Add `RequiresSerializerAttribute` to the CacheHandle

### ISSUE THREAD

**Issue by ndrwrbgs** [maldworth/CacheManager.FileCaching#5]
Not sure why `CacheManager` doesn't infer this from the `ctor` using `ICacheSerializer serializer`, but it gives a little better feedback when the attribute is present

**Comment by maldworth** [comment]
will do

**Comment by maldworth** [comment]
actually, is serialization required with FileCache? It's been a while since I've looked at this code, but here:

https://github.com/maldworth/CacheManager.FileCaching/blob/04a794e409b2df82a7cae8423db793dca1017e5b/src/CacheManager.FileCaching/FileCacheHandle.cs#L158

**Comment by ndrwrbgs** [comment]
Ah, but the CacheManager library throws for not supplying a serializer when
it uses reflection to try to find the right ctor. So in that case it might
just be a matter of adding another ctor, though _personally_ I'd prefer
forcing explicit serialization :)

**Comment by maldworth** [comment]
This should be fixed in the 1.2.0 release.
